RadioSolution\StaticContentBundle\Entity\StaticContent:
  type: entity
  table: static_content
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
    introduction:
      type: string
      length: 255
      nullable: true
    body:
      type: text
    date_add:
      type: datetime
    slug:
      type: string
      gedmo:
        slug:
          fields:
            - name
    order_content:
      type: integer
      default: 10
    published:
      type: boolean
      nullable: true
      default: 1
  oneToOne:
    image:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: id_image
        referencedColumnName: id
        onDelete: "SET NULL"
  manyToOne:
    categoryStaticContent:
      targetEntity: CategoryStaticContent
      #inversedBy: contents
      joinColumn:
        name: id_category
        referencedColumnName: id
        onDelete: "SET NULL"
