RadioSolution\ProgramBundle\Entity\Broadcast:
  type: entity
  table: music__broadcast
  lifecycleCallbacks:
    prePersist: [ updatedTimestamps ]
    preUpdate: [ updatedTimestamps ]
  indexes:
      created_index:
        columns: [ created_at ]
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    terms:
          type: string
          length: 255
          nullable: true
          default: NULL
    broadcasted:
      type: datetime
      nullable: true
      default: NULL
    created_at:
      type: datetime
    updated_at:
      type: datetime
  manyToOne:
    track:
      nullable: true
      default: NULL
      targetEntity: Track
      inversedBy: broadcasts
      joinColumn:
        name: track_id
        referencedColumnName: id


