RadioSolution\ProgramBundle\Entity\EmissionTheme:
  type: entity
  table: program__emission_theme
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
    description:
      type: string
  manyToOne:
    type:
      targetEntity: ThemeColor
      joinColumn:
        name: id_color
        referencedColumnName: id
