RadioSolution\ProgramBundle\Entity\Emission:
  type: entity
  table: program__emission
  lifecycleCallbacks:
    prePersist: [ updatedTimestamps ]
    preUpdate: [ updatedTimestamps ]
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 100
    description:
      type: text
    diffusion_start:
      type: date
    diffusion_stop:
      type: date
      column: difusion_stop
    archive:
      type: boolean
    slug:
      type: string
    created_at:
      type: datetime
      default: 'NOW()'
    updated_at:
      type: datetime
      default: 'NOW()'
  manyToOne:
    theme:
      targetEntity: EmissionTheme
      joinColumn:
        name: id_theme
        referencedColumnName: id
    collection:
      targetEntity: Application\Sonata\ClassificationBundle\Entity\Collection
      joinColumn:
        name: collection_id
        referencedColumnName: id
    frequency:
      targetEntity: EmissionFrequency
      joinColumn:
        name: id_frequency
        referencedColumnName: id
    group:
      targetEntity: Application\Sonata\UserBundle\Entity\Group
      joinColumn:
        name: id_group
        referencedColumnName: id
    media:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: id_media
        referencedColumnName: id
        onDelete: "SET NULL"
  oneToMany:
    exceptionalBroadcasts:
      targetEntity: ExceptionalBroadcast
      cascade: [all]
      mappedBy: Emission
      orphanRemoval: true
    weeklyBroadcasts:
      targetEntity: WeeklyBroadcast
      cascade: [all]
      mappedBy: Emission
      orphanRemoval: true
    programs:
      targetEntity: Program
      cascade: [all]
      mappedBy: emission
      orphanRemoval: true
