RadioSolution\ProgramBundle\Entity\Label:
  type: entity
  repositoryClass: RadioSolution\ProgramBundle\Entity\MusicRepository
  table: music__label
  lifecycleCallbacks:
    prePersist: [ updatedTimestamps ]
    preUpdate: [ updatedTimestamps ]
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
    resume:
      type: text
      nullable: true
    content:
      type: text
      nullable: true
    featuredFrom:
      type: date
      nullable: true
      default: NULL
    featuredTo:
      type: date
      nullable: true
      default: NULL
    slug:
      type: string
      gedmo:
        slug:
          #separator: -
          #style: default
          #unique: true
          fields:
            - title
    published:
      type: boolean
      nullable: true
    created_at:
      type: datetime
      default: 'NOW()'
    updated_at:
      type: datetime
      default: 'NOW()'

  oneToMany:
    albums:
      targetEntity: Album
      cascade: [persist, detach]
      mappedBy: labelId

  manyToOne:
    image:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      nullable: true
      joinColumn:
        name: image
        referencedColumnName: id
        onDelete: "SET NULL"


