RadioSolution\ProgramBundle\Entity\Label:
  type: entity
  table: music__label
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    date:
      type: datetime
    title:
      type: string
    resume:
      type: text
      nullable: true
    content:
      type: text
      nullable: true
    slug:
      type: string
      gedmo:
        slug:
          #separator: -
          #style: default
          #unique: true
          fields:
            - title
    published:
      type: boolean
      nullable: true

  lifecycleCallbacks:
    prePersist: [ prePersist ]
    preUpdate: [ preUpdate ]

  oneToMany:
    albums:
      targetEntity: Album
      cascade: [all]
      mappedBy: labelId

  manyToOne:
    image:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      nullable: true
      joinColumn:
        name: image
        referencedColumnName: id


