RadioSolution\ProgramBundle\Entity\Playlist:
  type: entity
  repositoryClass: RadioSolution\ProgramBundle\Entity\MusicRepository
  table: music__playlist
  lifecycleCallbacks:
    prePersist: [ updatedTimestamps ]
    preUpdate: [ updatedTimestamps ]
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
    featuredFrom:
      type: date
      nullable: true
      default: NULL
    featuredTo:
      type: date
      nullable: true
      default: NULL
    created_at:
      type: datetime
    updated_at:
      type: datetime
    published:
      type: boolean
      nullable: true
    slug:
      type: string
      gedmo:
        slug:
          #separator: -
          #style: default
          #unique: true
          fields:
            - title
    resume:
      type: text
      nullable: true
    content:
      type: text
      nullable: true
  manyToMany:
    albums:
      targetEntity: Album
      inversedBy: playlists
      cascade: [persist, detach, refresh]
      joinTable:
        name: music__albums_playlists
        joinColumns:
          playlist_id:
            referencedColumnName: id
        inverseJoinColumns:
          album_id:
            referencedColumnName: id

