RadioSolution\ProgramBundle\Entity\Program:
  type: entity
  table: program__program
  lifecycleCallbacks:
    prePersist: [ updatedTimestamps ]
    preUpdate: [ updatedTimestamps ]
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    time_start:
      type: datetime
    time_stop:
      type: datetime
    collision:
      type: boolean
      nullable: true
      default: false
    created_at:
      type: datetime
      default: 'NOW()'
    updated_at:
      type: datetime
      default: 'NOW()'
  oneToOne:
    podcast:
      nullable: true
      default: NULL
      targetEntity: RadioSolution\PodcastBundle\Entity\Podcast
      inversedBy: program
      joinColumn:
        name: id_podcast
        referencedColumnName: id
  manyToOne:
    emission:
      targetEntity: Emission
      inversedBy: programs
      joinColumn:
        name: id_emission
        referencedColumnName: id
