RadioSolution\RSSAgregatorBundle\Entity\RSSagregator:
  type: entity
  table: rss_agregator_conteneur
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string