RadioSolution\ContactBundle\Entity\Contact:
  type: entity
  table: contact
  lifecycleCallbacks:
    prePersist: [ prePersist ]
    preUpdate: [ preUpdate ]
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
    name:
      type: string
      length: 255
    email:
      type: string
      length: 255
    position:
      type: integer
    created_at:
      type: datetime
    updated_at:
      type: datetime
