imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata.yml }
    - { resource: radiosolution.yml }
    - { resource: @ApplicationSonataMediaBundle/Resources/config/services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
#parameters:
#    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'PodcastBundle:Form:podcast_player.html.twig'
            - 'PodcastBundle:Form:podcast_marker.html.twig'
    globals:
        liveStreamUrl: %liveStreamUrl%
        google_search_cx: %google_search_cx%
        ga_tracking_code: %ga_tracking_code%
        social_facebook_url: %social_facebook_url%
        social_facebook_app_id: %social_facebook_app_id%
        social_twitter_url: %social_twitter_url%
        social_twitter_username: %social_twitter_username%
        social_googleplus_url: %social_googleplus_url%
        social_flickr_url: %social_flickr_url%
        social_youtube_url: %social_youtube_url%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ "FOSCommentBundle" ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        #auto_generate_proxy_classes: "%kernel.debug%"
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true
        entity_managers:
            default:
                mappings:
                    ApplicationSonataAdminBundle: ~
                    SonataAdminBundle: ~
                    ApplicationSonataClassificationBundle: ~
                    SonataClassificationBundle: ~
                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~
                    ApplicationSonataNewsBundle: ~
                    SonataNewsBundle: ~
                    ApplicationSonataNotificationBundle: ~
                    SonataNotificationBundle: ~
                    ApplicationSonataPageBundle: ~
                    SonataPageBundle: ~
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~
                    FOSUserBundle: ~
                    ProgramBundle: ~
                    PodcastBundle: ~
                    MenuBundle: ~
                    SiteBundle: ~
                    StaticContentBundle: ~
                    ContactBundle: ~
                    #CarrouselBundle: ~
                    #PubBundle: ~
                    #SurveyBundle: ~
                    #RSSAgregatorBundle: ~


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    spool:     { type: memory }

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm

    service:
        user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm
    profile:  # Authentication Form
        form:
            type:               fos_user_profile
            handler:            fos_user.profile.form.handler.default
            name:               fos_user_profile_form
            validation_groups:  [Authentication] # Please note : this is not the default valu

cmf_routing:
    chain:
        routers_by_id:
            # enable the DynamicRouter with high priority to allow overwriting configured routes with content
            #cmf_routing.dynamic_router: 200
            # enable the symfony default router with a lower priority
            sonata.page.router: 150
            router.default: 100

# Recaptcha parameters
ewz_recaptcha:
    public_key:  %recaptcha_public_key%
    private_key: %recaptcha_private_key%
    locale_key:  %kernel.default_locale%
    ajax: false

# FOS comment bundle conf (uses FOS rest bundle)
fos_comment:
    db_driver: orm
    class:
        model:
            comment: MyProject\MyBundle\Entity\Comment
            thread: MyProject\MyBundle\Entity\Thread

#fos_comment_api:
#    type: rest
#    resource: "@FOSCommentBundle/Resources/config/routing.yml"
#    prefix: /api
#    defaults: { _format: html }

# CKEditor parameters
ivory_ck_editor:
    default_config: normal
    configs:
        mini:
            toolbar:
            - ['Source','-','Bold','Italic','Underline','-','Subscript','Superscript','-','RemoveFormat','-','Link','Unlink','Anchor']
            language: '%locale%'

        normal:
            toolbar:
            - [ 'Source','-','Bold','Italic','Underline','-','Subscript','Superscript','-','RemoveFormat','-','Link','Unlink','Anchor','-','NumberedList','BulletedList','-','Blockquote','-','JustifyLeft','JustifyCenter','JustifyRight' ]
            - [ 'Undo','Redo','-','PasteFromWord','PasteText','Format','Styles','-','Image','MediaEmbed','Audio','-','Table','-','SpecialChar','-','ShowBlocks' ]
            #contentsCss: /path/to/style.css
            #contentsLanguage: fr
            language: '%locale%'
            #stylesSet = [
            #    { name : 'Strong Emphasis', element : 'strong' }
            #    { name : 'Emphasis', element : 'em' }
            #]
            filebrowserBrowseRoute: admin_sonata_media_media_browser
            filebrowserImageBrowseRoute: admin_sonata_media_media_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_sonata_media_media_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_sonata_media_media_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: default # Optional, to upload in a custom context
            format_tags: 'p;h1;h2;h3;h4;h5;h6;address'
            extraPlugins: 'mediaembed' #widget,lineutils,oembed,Audio
            #removePlugins: 'iframe'

        plus:
            toolbar:
            #- [ 'Source','-','Bold','Italic','Underline','-','Subscript','Superscript','-','RemoveFormat','-','Link','Unlink','Anchor','-','NumberedList','BulletedList','-','Blockquote','-','JustifyLeft','JustifyCenter','JustifyRight' ]
            #- '/'
            #- [ 'Undo','Redo','-','PasteFromWord','PasteText','Format','Styles','-','Image','MediaEmbed','Audio','-','Table','-','SpecialChar','-','ShowBlocks' ]
            #- '/'
            #- [ 'Find','Replace','-','HorizontalRule','-','SpellChecker','-','Maximize' ]
            - [ 'Source' ]
            - [ 'Styles', 'Format', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight' ]
            - [ 'TextColor', 'BGColor' ]
            - [ 'Image', 'MediaEmbed', 'Audio', '-', 'Table', 'HorizontalRule', 'SpecialChar' ]
            - '/'
            - [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ]
            - [ 'NumberedList', 'BulletedList', '-', 'Blockquote' ]
            - [ 'Link', 'Unlink', 'Anchor' ]
            - '/'
            - ['Undo', 'Redo', '-','PasteText', 'PasteFromWord']
            - [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ]
            - [ 'Maximize', 'ShowBlocks' ]
            language: '%locale%'
            filebrowserBrowseRoute: admin_sonata_media_media_browser
            filebrowserImageBrowseRoute: admin_sonata_media_media_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_sonata_media_media_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_sonata_media_media_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: default # Optional, to upload in a custom context
            format_tags: 'p;h1;h2;h3;h4;h5;h6;pre;address;div'
            extraPlugins: 'mediaembed' #widget,lineutils,oembed,Audio
            #removePlugins: 'iframe'

    toolbars:
        configs:
            custom_mini: [ "@basic_editing" ]
            custom_normal: [ "@normal_editing",'/','@normal_authoring' ]
            custom_full: [ "@normal_editing",'/','@normal_authoring','/','@extended_authoring' ] #[ [ "@document",'-',"@basicstyles",'-',"@paragraph",'-',"@alignement",'-',"@links" ], '/', [ 'Format','Styles','-','Image','Flash','MediaEmbed','Audio','-','Table','HorizontalRule','-','SpecialChar'], '/', [ 'Undo','Redo','-','PasteFromWord','PasteText', 'Find','Replace','-','SelectAll','-','SpellChecker','-','Maximize','ShowBlocks' ] ]
        items:
            basic_editing: [ 'Source','-','Bold','Italic','Underline','-','Subscript','Superscript','-','RemoveFormat','-','Link','Unlink','Anchor' ]
            normal_editing: [ 'Source','-','Bold','Italic','Underline','-','Subscript','Superscript','-','RemoveFormat','-','Link','Unlink','Anchor','-','NumberedList','BulletedList','-','Blockquote','-','JustifyLeft','JustifyCenter','JustifyRight' ]
            normal_authoring: [ 'Undo','Redo','-','PasteFromWord','PasteText','Format','Styles','-','Image','MediaEmbed','Audio','-','Table','-','SpecialChar','-','ShowBlocks' ]
            extended_authoring: [ 'Find','Replace','-','HorizontalRule','-','SpellChecker','-','Maximize' ]
        #    insert: [ 'Image','Flash','-','Table','HorizontalRule','-','SpecialChar' ]
        #    styles: [ 'Styles','Format']
        #    colors: [ 'TextColor','BGColor' ]
        #    tools: [ 'Maximize', 'ShowBlocks' ]
    plugins:
        #oembed:
        #    path:     "/bundles/applicationivoryckeditor/ckeditor/plugins/oembed/"
        #    filename: "plugin.js"
        mediaembed:
            path:     "/bundles/applicationivoryckeditor/ckeditor/plugins/mediaembed/"
            filename: "plugin.js"
        #widget:
        #    path:     "/bundles/applicationivoryckeditor/ckeditor/plugins/widget/"
        #    filename: "plugin.js"
        #lineutils:
        #    path:     "/bundles/applicationivoryckeditor/ckeditor/plugins/lineutils/"
        #    filename: "plugin.js"
        #Audio:
        #    path:     "/bundles/applicationivoryckeditor/ckeditor/plugins/Audio/"
        #    filename: "plugin.js"

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: SiteBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

stof_doctrine_extensions:
    orm:
        default:
            sortable:      true
            sluggable:     true

hype_mailchimp:
    api_key: %mailchimp_api_key%
    default_list: %mailchimp_default_list%

white_october_breadcrumbs:
    #separator:          ''
    #separatorClass:     ''
    #listId:             'wo-breadcrumbs'
    listClass:          'breadcrumb'
    itemClass:          'breadcrumb-item'
    linkRel:            ''
    locale:             ~ # defaults to null, so the default locale is used
    translation_domain: ~ # defaults to null, so the default domain is used
    viewTemplate:       SiteBundle:Breadcrumbs:breadcrumbs.html.twig

mremi_url_shortener:
    link_class: RadioSolution\SiteBundle\Entity\Link

    providers:
        bitly:
            enabled:             true
            username:            %bitly_username%
            password:            %bitly_password%
            options:
                connect_timeout: 3
                timeout:         10

        #google:
        #    enabled:             true
        #    api_key:             your_api_key
        #    options:
        #        connect_timeout: 1
        #        timeout:         1
