services:
    radioSolution.program.emission:
        class: RadioSolution\ProgramBundle\Admin\EmissionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Programmation', label: 'Émissions' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\Emission, "ProgramBundle:CRUD"]

    radioSolution.program.emissionTheme:
        class: RadioSolution\ProgramBundle\Admin\EmissionThemeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Programmation', label: 'Thèmes' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\EmissionTheme, "SonataAdminBundle:CRUD"]

    radioSolution.program.emissionFrequency:
        class: RadioSolution\ProgramBundle\Admin\EmissionFrequencyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Programmation', label: 'Fréquences de diffusion' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\EmissionFrequency, "SonataAdminBundle:CRUD"]

    radioSolution.program.ExceptionalBroadcast:
        class: RadioSolution\ProgramBundle\Admin\ExceptionalBroadcastAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Programmation', label: 'Émissions exceptionnelles', show_in_dashboard: false }
        arguments: [null, RadioSolution\ProgramBundle\Entity\ExceptionalBroadcast, "SonataAdminBundle:CRUD"]

    radioSolution.program.WeeklyBroadcast:
        class: RadioSolution\ProgramBundle\Admin\WeeklyBroadcastAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Programmation', label: 'Émissions hebdo', show_in_dashboard: false }
        arguments: [null, RadioSolution\ProgramBundle\Entity\WeeklyBroadcast, "SonataAdminBundle:CRUD"]

    radioSolution.program.themeColor:
        class: RadioSolution\ProgramBundle\Admin\ThemeColorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Programmation', label: 'Couleurs du thème' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\ThemeColor, "SonataAdminBundle:CRUD"]

    radioSolution.program.program:
        class: RadioSolution\ProgramBundle\Admin\ProgramAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Programmation', label: 'Programmes' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\Program, "SonataAdminBundle:CRUD"]

    radioSolution.program.album:
        class: RadioSolution\ProgramBundle\Admin\AlbumAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Musique', label: 'Albums' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\Album, "ProgramBundle:CRUD"]

    radioSolution.program.track:
        class: RadioSolution\ProgramBundle\Admin\TrackAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Musique', label: 'Tracks' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\Track, "SonataAdminBundle:CRUD"]

    radioSolution.program.playlist:
        class: RadioSolution\ProgramBundle\Admin\PlaylistAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Musique', label: 'Playlists' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\Playlist, "ProgramBundle:CRUD"]

    radioSolution.program.label:
        class: RadioSolution\ProgramBundle\Admin\LabelAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Musique', label: 'Labels' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\Label, "ProgramBundle:CRUD"]

    radioSolution.podcast.podcast:
        class: RadioSolution\PodcastBundle\Admin\PodcastAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Podcasts', label: 'Podcasts' }
        arguments: [null, RadioSolution\PodcastBundle\Entity\Podcast, "SonataAdminBundle:CRUD"]

    radioSolution.menu.menu:
        class: RadioSolution\MenuBundle\Admin\MenuAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Menus', label: 'Menus' }
        arguments: [null, RadioSolution\MenuBundle\Entity\Menu, "SonataAdminBundle:CRUD"]

    radioSolution.menu.item:
        class: RadioSolution\MenuBundle\Admin\ItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Menus', label: 'Entrées' }
        arguments: [null, RadioSolution\MenuBundle\Entity\Item, "SonataAdminBundle:CRUD"]

    radioSolution.carrousel.slider:
        class: RadioSolution\CarrouselBundle\Admin\SliderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Blocs personnalisés', label: 'Carousels' }
        arguments: [null, RadioSolution\CarrouselBundle\Entity\Slider, "SonataAdminBundle:CRUD"]

    radioSolution.carrousel.item:
        class: RadioSolution\CarrouselBundle\Admin\ItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Blocs personnalisés', label: 'Éléments de carousel'}
        arguments: [null, RadioSolution\CarrouselBundle\Entity\Item, "SonataAdminBundle:CRUD"]

    radioSolution.carrousel.customItem:
        class: RadioSolution\CarrouselBundle\Admin\CustomItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Blocs personnalisés', label: 'Éléments de carousel personnalisés'}
        arguments: [null, RadioSolution\CarrouselBundle\Entity\CustomItem, "SonataAdminBundle:CRUD"]

    radioSolution.staticContent.staticContent:
        class: RadioSolution\StaticContentBundle\Admin\StaticContentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sonata_page, label_catalogue: "%sonata.page.admin.site.translation_domain%", label: "Contenus statiques", label_translator_strategy: "sonata.admin.label.strategy.underscore"}
        arguments: [null, RadioSolution\StaticContentBundle\Entity\StaticContent, "SonataAdminBundle:CRUD"]

    radioSolution.staticContent.CategorystaticContent:
        class: RadioSolution\StaticContentBundle\Admin\CategoryStaticContentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sonata_page, label_catalogue: "%sonata.page.admin.site.translation_domain%", label: "Catégories contenus statiques", label_translator_strategy: "sonata.admin.label.strategy.underscore"}
        arguments: [null, RadioSolution\StaticContentBundle\Entity\CategoryStaticContent, "SonataAdminBundle:CRUD"]

    radioSolution.staticContent.DailymediastaticContent:
        class: RadioSolution\StaticContentBundle\Admin\DailymediaStaticContentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Blocs personnalisés', label_catalogue: "%sonata.page.admin.site.translation_domain%", label: "Dailymedia contenus statiques", label_translator_strategy: "sonata.admin.label.strategy.underscore"}
        arguments: [null, RadioSolution\StaticContentBundle\Entity\DailymediaStaticContent, "SonataAdminBundle:CRUD"]

    radioSolution.pub.pub:
        class: RadioSolution\PubBundle\Admin\PubAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Blocs personnalisés', label: 'Pub' }
        arguments: [null, RadioSolution\PubBundle\Entity\Pub, "SonataAdminBundle:CRUD"]

    radioSolution.Survey.Survey:
        class: RadioSolution\SurveyBundle\Admin\SurveyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Blocs personnalisés', label: 'Sondages' }
        arguments: [null, RadioSolution\SurveyBundle\Entity\Survey, "SonataAdminBundle:CRUD"]

    radioSolution.RSSAgregator.RSSfile:
        class: RadioSolution\RSSAgregatorBundle\Admin\RSSAgregatorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Blocs personnalisés', label: 'Agrégateur RSS' }
        arguments: [null, RadioSolution\RSSAgregatorBundle\Entity\RSSfile, "SonataAdminBundle:CRUD"]

    radioSolution.RSSAgregator.RSSagregator:
        class: RadioSolution\RSSAgregatorBundle\Admin\RSSAgregatorContenerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Blocs personnalisés', label: 'Conteneur d’agrégateurs RSS' }
        arguments: [null, RadioSolution\RSSAgregatorBundle\Entity\RSSagregator, "SonataAdminBundle:CRUD"]

