services:
    radioSolution.program.emission:
        class: RadioSolution\ProgramBundle\Admin\EmissionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Programme', label: 'Émissions' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\Emission, "SonataAdminBundle:CRUD"]

    radioSolution.program.emissionTheme:
        class: RadioSolution\ProgramBundle\Admin\EmissionThemeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Programme', label: 'Thèmes' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\EmissionTheme, "SonataAdminBundle:CRUD"]

    radioSolution.program.emissionFrequency:
        class: RadioSolution\ProgramBundle\Admin\EmissionFrequencyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Programme', label: 'Fréquence' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\EmissionFrequency, "SonataAdminBundle:CRUD"]

    radioSolution.program.ExceptionalBroadcast:
        class: RadioSolution\ProgramBundle\Admin\ExceptionalBroadcastAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Programme', label: 'Émissions exceptionnelles' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\ExceptionalBroadcast, "SonataAdminBundle:CRUD"]

    radioSolution.program.WeeklyBroadcast:
        class: RadioSolution\ProgramBundle\Admin\WeeklyBroadcastAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Programme', label: 'Émissions hebdo' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\WeeklyBroadcast, "SonataAdminBundle:CRUD"]

    radioSolution.program.themeColor:
        class: RadioSolution\ProgramBundle\Admin\ThemeColorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Programme', label: 'Couleur du thème' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\ThemeColor, "SonataAdminBundle:CRUD"]

    radioSolution.program.program:
        class: RadioSolution\ProgramBundle\Admin\ProgramAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Programme', label: 'Programme' }
        arguments: [null, RadioSolution\ProgramBundle\Entity\Program, "SonataAdminBundle:CRUD"]

    radioSolution.podcast.podcast:
        class: RadioSolution\PodcastBundle\Admin\PodcastAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Podcast', label: 'Podcasts' }
        arguments: [null, RadioSolution\PodcastBundle\Entity\Podcast, "SonataAdminBundle:CRUD"]

    radioSolution.menu.menu:
        class: RadioSolution\MenuBundle\Admin\MenuAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Menus', label: 'Menus' }
        arguments: [null, RadioSolution\MenuBundle\Entity\Menu, "SonataAdminBundle:CRUD"]

    radioSolution.menu.item:
        class: RadioSolution\MenuBundle\Admin\ItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Menus', label: 'Entrées' }
        arguments: [null, RadioSolution\MenuBundle\Entity\Item, "SonataAdminBundle:CRUD"]

    radioSolution.carrousel.slider:
        class: RadioSolution\CarrouselBundle\Admin\SliderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Blocs personnalisés', label: 'Carousels' }
        arguments: [null, RadioSolution\CarrouselBundle\Entity\Slider, "SonataAdminBundle:CRUD"]

    radioSolution.carrousel.item:
        class: RadioSolution\CarrouselBundle\Admin\ItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Blocs personnalisés', label: 'Éléments de carousel'}
        arguments: [null, RadioSolution\CarrouselBundle\Entity\Item, "SonataAdminBundle:CRUD"]

    radioSolution.carrousel.customItem:
        class: RadioSolution\CarrouselBundle\Admin\CustomItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Blocs personnalisés', label: 'Éléments de carousel personnalisés'}
        arguments: [null, RadioSolution\CarrouselBundle\Entity\CustomItem, "SonataAdminBundle:CRUD"]

    radioSolution.staticContent.staticContent:
        class: RadioSolution\StaticContentBundle\Admin\StaticContentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sonata_page, label_catalogue: "%sonata.page.admin.site.translation_domain%", label: "Contenus statiques", label_translator_strategy: "sonata.admin.label.strategy.underscore"}
        arguments: [null, RadioSolution\StaticContentBundle\Entity\StaticContent, "SonataAdminBundle:CRUD"]

    radioSolution.staticContent.CategorystaticContent:
        class: RadioSolution\StaticContentBundle\Admin\CategoryStaticContentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sonata_page, label_catalogue: "%sonata.page.admin.site.translation_domain%", label: "Catégories contenus statiques", label_translator_strategy: "sonata.admin.label.strategy.underscore"}
        arguments: [null, RadioSolution\StaticContentBundle\Entity\CategoryStaticContent, "SonataAdminBundle:CRUD"]

    radioSolution.staticContent.DailymediastaticContent:
        class: RadioSolution\StaticContentBundle\Admin\DailymediaStaticContentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Blocs personnalisés', label_catalogue: "%sonata.page.admin.site.translation_domain%", label: "Dailymedia contenus statiques", label_translator_strategy: "sonata.admin.label.strategy.underscore"}
        arguments: [null, RadioSolution\StaticContentBundle\Entity\DailymediaStaticContent, "SonataAdminBundle:CRUD"]

