app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Sonata Override
NewsBundle:
    resource: "@SonataNewsBundle/Resources/config/routing.yml"
    prefix:   /

# RadioSolution
ProgramBundle:
    resource: "@ProgramBundle/Resources/config/routing.yml"
    prefix:   /

PodcastBundle:
    resource: "@PodcastBundle/Resources/config/routing.yml"
    prefix:   /

StaticContentBundle:
    resource: "@StaticContentBundle/Resources/config/routing/staticcontent.yml"
    prefix:   /

ContactBundle:
    resource: "@ContactBundle/Resources/config/routing.yml"
    prefix:   /

SearchBundle:
    resource: "@SearchBundle/Resources/config/routing.yml"
    prefix:   /

SiteBundle:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

MenuBundle:
    resource: "@MenuBundle/Resources/config/routing.yml"
    prefix:   /

# Sonata
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

#sonata_user_security:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

#sonata_user_resetting:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
#    prefix: /resetting

#sonata_user_profile:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
#    prefix: /profile

#sonata_user_register:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
#    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_page_exceptions:
    resource: '@SonataPageBundle/Resources/config/routing/exceptions.xml'
    prefix: /

sonata_page_cache:
    resource: '@SonataPageBundle/Resources/config/routing/cache.xml'
    prefix: /

news:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /news

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
