<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\NewsBundle\Entity;

use Sonata\NewsBundle\Entity\BasePost as BasePost;


/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Post extends BasePost
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var string $admin_title
     */
    protected $admin_title;

    /**
     * @var podcast $podcast
     */
    protected $podcast;

    /**
     * @var Application\Sonata\MediaBundle\Entity\Media
     */
    protected $image;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get podcast
     *
     * @return Podcast $podcast
     */
    public function getPodcast()
    {
        return $this->podcast;
    }


    public function getFilePodcast()
    {
        return $this->podcast->getFilePodcast()->getProviderReference();
    }

    public function getMediaPodcast()
    {
        if ($this->podcast!=NULL)
        return $this->podcast->getFilePodcast();
    }

    /**
     * Get podcast
     *
     * @return Podcast $podcast
     */
    public function setPodcast(\RadioSolution\PodcastBundle\Entity\Podcast $podcast)
    {
        $this->podcast=$podcast;
    }

    public function getImage()
    {

        if(!$this->image){

            if($this->getPodcast()){

                $podcast = $this->getPodcast();

                if($podcast->getEmission()){

                    $this->image =$podcast->getImageEmission();

                }

            }

        }

        return $this->image;

    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    /**
     * Gets the value of admin_title.
     *
     * @return string $admin_title
     */
    public function getAdminTitle()
    {
        return $this->admin_title;
    }

    /**
     * Sets the value of admin_title.
     *
     * @param string $admin_title $admin_title the admin title
     *
     * @return self
     */
    public function setAdminTitle($admin_title)
    {
        $this->admin_title = $admin_title;

        return $this;
    }
}
