static_content:
    path:  /article/{slug}
    defaults: { _controller: "StaticContentBundle:StaticContent:show" }

static_content_categories:
    path:  /list-categorie/{slug}
    defaults: { _controller: "StaticContentBundle:StaticContent:showList" }

static_content_categorie:
    path:  /categorie/{slug}
    defaults: { _controller: "StaticContentBundle:StaticContent:showCategorie" }
