#PodcastBundle_homepage:
#    path:  /podcasts
#    defaults: { _controller: "PodcastBundle:Podcast:index" }

podcast_embed:
    path: /embed/podcast/{id}
    defaults: { _controller: "PodcastBundle:Podcast:embed" }
#PodcastBundle_show:
#    path:  /podcast/{id}
#    defaults: { _controller: "PodcastBundle:Podcast:show" }
#PodcastBundle_date:
#    path:  /podcasts-date/{date}
#    defaults: { _controller: "PodcastBundle:Podcast:indexDate" }

