PodcastBundle_homepage:
    path:  /podcasts
    defaults: { _controller: "PodcastBundle:Podcast:index" }
#PodcastBundle_show:
#    path:  /podcast/{id}
#    defaults: { _controller: "PodcastBundle:Podcast:show" }
#PodcastBundle_date:
#    path:  /podcasts-date/{date}
#    defaults: { _controller: "PodcastBundle:Podcast:indexDate" }

