emissions:
    path:  emissions
    defaults: { _controller: "ProgramBundle:Emission:index" }
emission:
    path:  emission/{name}
    defaults: { _controller: "ProgramBundle:Emission:show" }
emissionrss:
    path:  rss/emission/{name}.{_format}
    defaults: { _controller: "ProgramBundle:Emission:showRss", _format: xml  }
programs:
    path:  programmes.{_format}
    defaults: { _controller: "ProgramBundle:Program:index", _format: html }
    requirements:
      _format:  html|pdf
ecoute:
    path:  ecoute
    defaults: { _controller: "ProgramBundle:Ecoute:index"}
    requirements:
       methods:  GET|POST
onair:
    pattern:  onair
    defaults: { _controller: "ProgramBundle:Program:onair"}
whoami:
    pattern:  whoami
    defaults: { _controller: "ProgramBundle:WhoAmI:index"}

labels:
    path: labels
    defaults: { _controller: "ProgramBundle:Label:index" }

label:
    path: label/{slug}
    defaults: { _controller: "ProgramBundle:Label:show" }
    requirements:
        slug: "[a-zA-Z0-9-_/]+"

albums:
    path: albums
    defaults: { _controller: "ProgramBundle:Album:index" }

album:
    path: album/{slug}
    defaults: { _controller: "ProgramBundle:Album:show" }
    requirements:
        slug: "[a-zA-Z0-9-_/]+"

album_finder:
    path: album/find/{terms}
    defaults: { _controller: "ProgramBundle:Album:find" }

playlists:
    path: playlists
    defaults: { _controller: "ProgramBundle:Playlist:index" }

playlist:
    path: playlist/{slug}
    defaults: { _controller: "ProgramBundle:Playlist:show" }
    requirements:
        slug: "[a-zA-Z0-9-_/]+"

broadcast:
    path: c-est-quoi-ce-titre
    defaults: { _controller: "ProgramBundle:Broadcast:index" }
