emissions:
    path:  emissions
    defaults: { _controller: "ProgramBundle:Emission:index" }
emission:
    path:  emission/{name}
    defaults: { _controller: "ProgramBundle:Emission:show" }
emissionrss:
    path:  rss/emission/{name}.{_format}
    defaults: { _controller: "ProgramBundle:Emission:showRss", _format: xml  }
programs:
    path:  programmes.{_format}
    defaults: { _controller: "ProgramBundle:Program:index", _format: html }
    requirements:
      _format:  html|pdf
ecoute:
    path:  ecoute
    defaults: { _controller: "ProgramBundle:Ecoute:index"}
    requirements:
       methods:  GET|POST
onair:
    path:  onair
    defaults: { _controller: "ProgramBundle:Program:onair"}
