parameters:
#    program.example.class: RadioSolution\ProgramBundle\Example

services:
    radiosolution.program.trackRetriever:
        class: RadioSolution\ProgramBundle\Service\Tracks\TrackRetriever
        arguments:
            - "@service_container"
            - "%locale%"
            - "%amazon_ws_api_key%"
            - "%amazon_ws_api_secret_key%"
            - "%amazon_ws_api_associate_tag%"
    radiosolution.program.nowPlaying:
        class: RadioSolution\ProgramBundle\Service\Tracks\NowPlaying
        arguments:
            - "@service_container"
            - "%nowplayingurl%"

