home:
    path: /
    defaults: { _controller: "SiteBundle:Home:index" }

newsletter_subscription:
    path:  newsletter/subscribe
    defaults: { _controller: "SiteBundle:Newsletter:subscribe" }

xml_sitemap:
  path: "/sitemap.{_format}"
  defaults: { _controller: "SiteBundle:XMLSitemap:index" }
  requirements: { _format: xml }

