RadioSolution\MenuBundle\Entity\Menu:
  type: entity
  table: menu__menu
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255

  oneToMany:
    items:
      targetEntity: Item
      mappedBy: menu
      cascade: [all]
